### ISSUE TITLE
Oh No Minigame Enhances Are Broken

### ISSUE THREAD

**Issue by NotAJumbleOfNumbers** [Telnaior/RtaB6#79]
It's been a while since someone used the issue reporter, no?  Anyways here's my formal request to Make Enhances Less Broken:tm:

TOO STRONG

Zilch - Zilch
2s will now score 20 points.

Safe - Safe Cracker
You will be given an extra attempt to crack your chosen safe.

TOO WEAK

Cards - Money Cards
A paired card will count as a win.

Bumper - Bumper Grab
Exits will not vanish and can be revisited.
(also, this game might need a buff in general.  and that "$100 on me line" should be reworked to also respawn you in the center)

**Comment by TemperGrace** [comment]
Ultimately, the decision won't fall to me - however; having been the one to design the Safe Cracker enhancement, I have been saying it's broken since before the minigame even went live and I'm glad people have *finally* realised this. It was actually even stronger last season in theory; it just flew under the radar! It's nice to have it have some time in the sun.

Just to make sure that the behind-the-scenes understanding is documented here, the Safe Cracker enhancement gives Safe an EV of about $1.5m per play if used optimally when playing a LOLN style over a whole season. This is **far and away** the highest minigame EV of all. The enhancement accounts for about 67% of this value; making it one of the most impactful enhancements in its own right. Even if you play for the silver rather than the gold, the EV is still very high, and it's not even playing for random big jackpots - it's far more consistent than anything else in S12.

With that understanding in mind, reducing the value of the *minigame* would make it suck too much without the enhancement (it doesn't overperform by default), so adjusting the enhancement is likely the correct play forward.

So... what should it be redesigned towards?

**Comment by NotAJumbleOfNumbers** [comment]
Oh I forgot to mention this in the 'too weak' category:
Star - Stardust
The value of non-star spaces are doubled.
Though honestly I think this minigame needs a complete overhaul, it's just...boring.

**Comment by CaptainMeme** [comment]
re: Safe...
"You will be shown the correct placement of a single digit at the beginning of the game" seems much less powerful but still helpful. Quite dull though.
"At the beginning of the game, you will be shown a combination with zero digits correct" could be another option and is a weaker version of the current enhancement, although might still be too strong.

**Comment by NotAJumbleOfNumbers** [comment]
Changing how the game works mechanically is bound to throw things out of whack somewhere, so I don't think we should even try going there.  Here's a different idea instead:
"For every digit you find in the first two guesses, the prize increases by 10%."

**Comment by NotAJumbleOfNumbers** [comment]
> re: Safe... "You will be shown the correct placement of a single digit at the beginning of the game" seems much less powerful but still helpful. Quite dull though.

It's actually *just* as powerful as the current enhance!

**Comment by Telnaior** [comment]
Money Cards enhancement has been changed in master. I've looked at "you receive one digit for free" in Safe Cracker and the numbers I've seen show it to be about half as powerful as the existing enhancement, which is still on the powerful end but brings it vaguely back into line.

**Comment by Telnaior** [comment]
All of these have been changed except for Zilch.
